### ISSUE TITLE
Key Agreement Calculation and ed448 Curve

### ISSUE THREAD

**Issue by Spomky** [encedo/php-ed25519-ext#3]
Hi,

Thank you for this nice PHP extension. I use it for my project and it works well.
It may not be the good place to ask my questions as it is partially related to this extension.
1. Could it be possible to implement a method for the [X25519 function](https://tools.ietf.org/html/draft-irtf-cfrg-curves-11#section-5) to allow us to encrypt/decrypt using this curve?
2. As the [IETF draft](https://tools.ietf.org/html/draft-irtf-cfrg-eddsa) introduces the curves ed25519 and ed448 and you already implemented ed25519, could it be possible to create a similar project or update this one to provide the ed448 curve?
3. If you agree with the two previous points, could it be possible to implement a method for the [X488 function](https://tools.ietf.org/html/draft-irtf-cfrg-curves-11#section-5) as well?

Thanks and Regards.

**Comment by encedo** [comment]
Hi

Use this extension https://github.com/encedo/php-curve25519-ext . It implement curve25519 and I'm using it a lot! ED25519 and curve25519 are not the same, look here: https://download.libsodium.org/doc/advanced/ed25519-curve25519.html (short: first for sign, other for key exchange)

However this extension has undocumented function curved25519_scalarmult_basepoint (not tested by me, placed as it is in original code). Hack it! Look into src code.

ED448 look promising and if find more free time I will do a PHP extention for ed448 (like this one). The original code is here: https://sourceforge.net/p/ed448goldilocks/code/ci/curve25519-work/tree/

Chris

**Comment by Spomky** [comment]
Thanks,

Thanks for the precision and links. I will try this other extension.
I use it in the [Jose context](https://tools.ietf.org/html/draft-ietf-jose-cfrg-curves).

**Comment by Spomky** [comment]
I tested the extension for curve25519 and it works fine. I will try to find more test vectors (I only have https://tools.ietf.org/html/draft-ietf-jose-cfrg-curves-01#appendix-A.6 in my Jose context).

While I was using this extension, I though about one idea: do you think it is possible to merge these extensions into one and provide methods that detect the algorithm to use according to the key size (or with an argument)?
I know this will induce a lot of time to spend to create a new project, but it will be easier for you to maintain it in the futur (only one repository, one documentation...) and for developpers (installation/packages...).

**Comment by Spomky** [comment]
Closing as the ed448 curve seems to be ignored in most projects in favor of ed25519.
